import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable, map, Subject } from 'rxjs';
import { environment } from '../../environments/environment';

export interface SubtitleTrack {
  lang: string;
  langName: string;
  isAutoGenerated: boolean;
  isTranslated: boolean;
  quality: 'high' | 'medium-high' | 'medium' | 'unsupported';
}

export interface AnalyzeResponse {
  videoId: string;
  tracks: SubtitleTrack[];
  videoTitle: string;
  videoDurationSeconds: number;
}

export interface SummarySection {
  heading: string;
  content: string;
}

export interface SummaryResponse {
  title: string;
  intro: string;
  sections: SummarySection[];
  keyPoints: string[];
  conclusion: string;
  lang: string;
  videoId: string;
}

export interface ArticleVariant {
  id: number;
  title: string;
  intro: string;
  sections: SummarySection[];
  keyPoints: string[];
  conclusion: string;
  isSpeed: boolean;
  createdAt: string;
}

export interface ByVideoResponse {
  videoId?: string;
  videoTitle?: string;
  videoUrl?: string;
  videoLang?: string;
  sourceLang?: string;
  articleLang?: string;
  metaTitle?: string;
  metaDescription?: string;
  previewImage?: string;
  transcript?: TranscriptSnippet[];
  categories?: Array<{ slug: string; label: string }>;
  screenshots?: VisualTimecode[];
  videoDuration?: number | null;
  videoPublishedAt?: string | null;
  createdAt?: string;
  variants: {
    full: ArticleVariant | null;
    medium: ArticleVariant | null;
    brief: ArticleVariant | null;
  };
}

export interface ArticleListItem {
  id: number;
  videoId: string;
  videoUrl: string;
  videoTitle: string;
  videoLang: string;
  sourceLang: string;
  articleLang: string;
  metaTitle: string | null;
  metaDescription: string | null;
  previewImage: string | null;
  createdAt: string;
  videoDuration: number | null;
  videoPublishedAt: string | null;
  title: string | null;
  intro: string | null;
  length: string | null;
  isSpeed: boolean | null;
  categories: Array<{ slug: string; label: string }>;
}

export interface ArticleListResponse {
  articles: ArticleListItem[];
  total: number;
  page: number;
  limit: number;
}

export interface ArticleCategoryWithCount {
  id: number;
  slug: string;
  label: string;
  count: number;
}

export interface ArticleListParams {
  page?: number;
  limit?: number;
  category?: string;
  lang?: string;
  dateFrom?: string;
  dateTo?: string;
  videoPublishedFrom?: string;
}

export interface TranscriptSnippet {
  start: number;
  text: string;
}

export interface VisualTimecode {
  seconds: number;
  label: string;
  reason: string;
  url?: string;
}

export type StreamEvent =
  | { type: 'transcript'; snippets: TranscriptSnippet[]; videoId: string }
  | { type: 'text'; chunk: string }
  | { type: 'error'; error: string };

export class ApiError extends Error {
  constructor(message: string, public status: number) {
    super(message);
  }
}

@Injectable({ providedIn: 'root' })
export class VideoApiService {
  private http = inject(HttpClient);
  private base = `${environment.apiUrl}/api/video`;

  resolveBaseUrl(): string {
    return environment.apiUrl;
  }

  analyze(url: string): Observable<AnalyzeResponse> {
    return this.http.post<AnalyzeResponse>(`${this.base}/analyze`, { url });
  }

  getVisualTimecodes(url: string, lang: string): Observable<VisualTimecode[]> {
    const subject = new Subject<VisualTimecode[]>();
    const controller = new AbortController();
    const endpoint = `${this.base}/visual-timecodes`;

    fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url, lang }),
      signal: controller.signal,
    }).then(async res => {
      if (!res.ok || !res.body) { subject.error(new Error(`HTTP ${res.status}`)); return; }
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() ?? '';
        for (const line of lines) {
          if (!line.startsWith('data: ')) continue;
          const data = line.slice(6).trim();
          if (data === '[DONE]') { subject.complete(); return; }
          try {
            const parsed = JSON.parse(data) as { timecodes: VisualTimecode[] };
            if (parsed.timecodes?.length) subject.next(parsed.timecodes);
          } catch {}
        }
      }
      subject.complete();
    }).catch(err => { if (err.name !== 'AbortError') subject.error(err); });

    return new Observable(observer => {
      const sub = subject.subscribe(observer);
      return () => { sub.unsubscribe(); controller.abort(); };
    });
  }

  getScreenshotUrl(url: string, seconds: number): string {
    return `${this.base}/screenshot?url=${encodeURIComponent(url)}&t=${seconds}`;
  }

  resolveScreenshotUrl(tc: VisualTimecode, videoUrl: string): string {
    if (tc.url) return `${environment.apiUrl}${tc.url}`;
    return this.getScreenshotUrl(videoUrl, tc.seconds);
  }

  getArticles(params: ArticleListParams): Observable<ArticleListResponse> {
    let p = new HttpParams();
    if (params.page   != null) p = p.set('page',     String(params.page));
    if (params.limit  != null) p = p.set('limit',    String(params.limit));
    if (params.category)       p = p.set('category', params.category);
    if (params.lang)           p = p.set('lang',     params.lang);
    if (params.dateFrom)           p = p.set('dateFrom',          params.dateFrom);
    if (params.dateTo)             p = p.set('dateTo',            params.dateTo);
    if (params.videoPublishedFrom) p = p.set('videoPublishedFrom', params.videoPublishedFrom);
    return this.http.get<ArticleListResponse>(`${environment.apiUrl}/api/articles`, { params: p });
  }

  getArticleCategories(): Observable<ArticleCategoryWithCount[]> {
    return this.http.get<ArticleCategoryWithCount[]>(`${environment.apiUrl}/api/articles/categories`);
  }

  getByVideo(videoId: string, lang: string, sourceLang?: string): Observable<ByVideoResponse> {
    const params: Record<string, string> = { v: videoId, lang };
    if (sourceLang && sourceLang !== lang) params['sourceLang'] = sourceLang;
    return this.http.get<ByVideoResponse>(`${environment.apiUrl}/api/articles/by-video`, { params });
  }

  summarizeStream(url: string, lang: string, tier: string, length: string, videoTitle?: string, nativeLang?: string): Observable<StreamEvent> {
    return new Observable(observer => {
      const controller = new AbortController();

      fetch(`${this.base}/summarize/stream`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, lang, tier, length, videoTitle, nativeLang }),
        signal: controller.signal,
      }).then(async res => {
        if (!res.ok) {
          const body = await res.json().catch(() => ({}));
          observer.error(new ApiError(body.error || `Server error ${res.status}`, res.status));
          return;
        }

        const reader = res.body!.getReader();
        const decoder = new TextDecoder();
        let buffer = '';
        let receivedDone = false;

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split('\n');
          buffer = lines.pop()!;

          for (const line of lines) {
            if (line.startsWith('data: ')) {
              const raw = line.slice(6).trim();
              if (raw === '[DONE]') {
                receivedDone = true;
                observer.complete();
                return;
              }
              try {
                const event = JSON.parse(raw) as StreamEvent;
                if (event.type === 'error') {
                  observer.error(new ApiError(event.error, 408));
                  return;
                }
                observer.next(event);
              } catch { /* skip malformed line */ }
            }
          }
        }
        if (!receivedDone) {
          observer.error(new Error('Connection closed before summary finished'));
        } else {
          observer.complete();
        }
      }).catch(err => observer.error(err));

      return () => controller.abort();
    });
  }
}
